// <auto-generated />
namespace MvcMusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MvcMuicStore_ini : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MvcMuicStore_ini));
        
        string IMigrationMetadata.Id
        {
            get { return "201805171213386_MvcMuicStore_ini"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
