// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMusicStore.Models;

namespace MvcMusicStore.Migrations
{
    [DbContext(typeof(MusicStoreDBContext))]
    partial class MusicStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029");

            modelBuilder.Entity("MvcMusicStore.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumArtUrl")
                        .HasMaxLength(1024);

                    b.Property<int>("ArtistId");

                    b.Property<int>("GenreId");

                    b.Property<decimal>("Price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Albums");

                    b.HasData(
                        new { AlbumId = 1, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 90, GenreId = 1, Price = 8.99m, Title = "The Best Of Men At Work" },
                        new { AlbumId = 2, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 1, GenreId = 10, Price = 8.99m, Title = "A Copland Celebration, Vol. I" },
                        new { AlbumId = 3, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 2, GenreId = 2, Price = 8.99m, Title = "Worlds" },
                        new { AlbumId = 4, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 3, GenreId = 1, Price = 8.99m, Title = "For Those About To Rock We Salute You" },
                        new { AlbumId = 5, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 3, GenreId = 1, Price = 8.99m, Title = "Let There Be Rock" },
                        new { AlbumId = 6, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 4, GenreId = 1, Price = 8.99m, Title = "Balls to the Wall" },
                        new { AlbumId = 7, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 4, GenreId = 1, Price = 8.99m, Title = "Restless and Wild" },
                        new { AlbumId = 8, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 5, GenreId = 10, Price = 8.99m, Title = "Górecki: Symphony No. 3" },
                        new { AlbumId = 9, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 6, GenreId = 1, Price = 8.99m, Title = "Big Ones" },
                        new { AlbumId = 10, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 7, GenreId = 2, Price = 8.99m, Title = "Quiet Songs" },
                        new { AlbumId = 11, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 8, GenreId = 1, Price = 8.99m, Title = "Jagged Little Pill" },
                        new { AlbumId = 12, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 10, GenreId = 1, Price = 8.99m, Title = "Facelift" },
                        new { AlbumId = 13, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 11, GenreId = 9, Price = 8.99m, Title = "Frank" },
                        new { AlbumId = 14, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 12, GenreId = 5, Price = 8.99m, Title = "Ring My Bell" },
                        new { AlbumId = 15, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 13, GenreId = 7, Price = 8.99m, Title = "Chill: Brazil (Disc 2)" },
                        new { AlbumId = 16, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 13, GenreId = 2, Price = 8.99m, Title = "Warner 25 Anos" },
                        new { AlbumId = 17, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 14, GenreId = 3, Price = 8.99m, Title = "Plays Metallica By Four Cellos" },
                        new { AlbumId = 18, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 15, GenreId = 4, Price = 8.99m, Title = "Revelations" },
                        new { AlbumId = 19, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 15, GenreId = 1, Price = 8.99m, Title = "Audioslave" },
                        new { AlbumId = 20, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 16, GenreId = 10, Price = 8.99m, Title = "The Last Night of the Proms" },
                        new { AlbumId = 21, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 17, GenreId = 10, Price = 8.99m, Title = "Sibelius: Finlandia" },
                        new { AlbumId = 22, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 18, GenreId = 10, Price = 8.99m, Title = "Mozart: Symphonies Nos. 40 & 41" },
                        new { AlbumId = 23, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 19, GenreId = 2, Price = 8.99m, Title = "The Best Of Billy Cobham" },
                        new { AlbumId = 24, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 20, GenreId = 3, Price = 8.99m, Title = "Alcohol Fueled Brewtality Live! [Disc 1]" },
                        new { AlbumId = 25, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 20, GenreId = 3, Price = 8.99m, Title = "Alcohol Fueled Brewtality Live! [Disc 2]" },
                        new { AlbumId = 26, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 21, GenreId = 3, Price = 8.99m, Title = "Black Sabbath Vol. 4 (Remaster)" },
                        new { AlbumId = 27, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 21, GenreId = 3, Price = 8.99m, Title = "Black Sabbath" },
                        new { AlbumId = 28, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 22, GenreId = 10, Price = 8.99m, Title = "Carmina Burana" },
                        new { AlbumId = 29, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 23, GenreId = 10, Price = 8.99m, Title = "A Soprano Inspired" },
                        new { AlbumId = 30, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 24, GenreId = 3, Price = 8.99m, Title = "Chemical Wedding" },
                        new { AlbumId = 31, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 26, GenreId = 7, Price = 8.99m, Title = "Prenda Minha" },
                        new { AlbumId = 32, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 26, GenreId = 7, Price = 8.99m, Title = "Sozinho Remix Ao Vivo" },
                        new { AlbumId = 33, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 27, GenreId = 4, Price = 8.99m, Title = "Cake: B-Sides and Rarities" },
                        new { AlbumId = 34, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 28, GenreId = 4, Price = 8.99m, Title = "Carried to Dust (Bonus Track Version)" },
                        new { AlbumId = 35, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 29, GenreId = 7, Price = 8.99m, Title = "Cássia Eller - Sem Limite [Disc 1]" },
                        new { AlbumId = 36, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 30, GenreId = 5, Price = 8.99m, Title = "Le Freak" },
                        new { AlbumId = 37, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 31, GenreId = 10, Price = 8.99m, Title = "Scheherazade" },
                        new { AlbumId = 38, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 32, GenreId = 7, Price = 8.99m, Title = "Minha Historia" },
                        new { AlbumId = 39, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 33, GenreId = 7, Price = 8.99m, Title = "Afrociberdelia" },
                        new { AlbumId = 40, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 33, GenreId = 7, Price = 8.99m, Title = "Da Lama Ao Caos" },
                        new { AlbumId = 41, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 35, GenreId = 4, Price = 8.99m, Title = "Carry On" },
                        new { AlbumId = 42, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 36, GenreId = 10, Price = 8.99m, Title = "SCRIABIN: Vers la flamme" },
                        new { AlbumId = 43, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 37, GenreId = 8, Price = 8.99m, Title = "Acústico MTV [Live]" },
                        new { AlbumId = 44, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 37, GenreId = 8, Price = 8.99m, Title = "Cidade Negra - Hits" },
                        new { AlbumId = 45, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 38, GenreId = 7, Price = 8.99m, Title = "Na Pista" },
                        new { AlbumId = 46, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 39, GenreId = 1, Price = 8.99m, Title = "Chronicle, Vol. 1" },
                        new { AlbumId = 47, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 39, GenreId = 1, Price = 8.99m, Title = "Chronicle, Vol. 2" },
                        new { AlbumId = 48, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 40, GenreId = 1, Price = 8.99m, Title = "Into The Light" },
                        new { AlbumId = 49, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "Come Taste The Band" },
                        new { AlbumId = 50, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "Deep Purple In Rock" },
                        new { AlbumId = 51, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "Fireball" },
                        new { AlbumId = 52, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "Machine Head" },
                        new { AlbumId = 53, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "MK III The Final Concerts [Disc 1]" },
                        new { AlbumId = 54, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "Purpendicular" },
                        new { AlbumId = 55, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "Slaves And Masters" },
                        new { AlbumId = 56, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "Stormbringer" },
                        new { AlbumId = 57, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "The Battle Rages On" },
                        new { AlbumId = 58, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 41, GenreId = 1, Price = 8.99m, Title = "The Final Concerts (Disc 2)" },
                        new { AlbumId = 59, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 42, GenreId = 2, Price = 8.99m, Title = "Outbreak" },
                        new { AlbumId = 60, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 43, GenreId = 7, Price = 8.99m, Title = "Djavan Ao Vivo - Vol. 02" },
                        new { AlbumId = 61, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 43, GenreId = 7, Price = 8.99m, Title = "Djavan Ao Vivo - Vol. 1" },
                        new { AlbumId = 62, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 44, GenreId = 5, Price = 8.99m, Title = "MacArthur Park Suite" },
                        new { AlbumId = 63, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 45, GenreId = 1, Price = 8.99m, Title = "Un-Led-Ed" },
                        new { AlbumId = 64, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 46, GenreId = 7, Price = 8.99m, Title = "The Best of Ed Motta" },
                        new { AlbumId = 65, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 47, GenreId = 10, Price = 8.99m, Title = "Adams, John: The Chairman Dances" },
                        new { AlbumId = 66, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 48, GenreId = 7, Price = 8.99m, Title = "Elis Regina-Minha História" },
                        new { AlbumId = 67, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 49, GenreId = 10, Price = 8.99m, Title = "Pachelbel: Canon & Gigue" },
                        new { AlbumId = 68, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 50, GenreId = 7, Price = 8.99m, Title = "Unplugged" },
                        new { AlbumId = 69, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 50, GenreId = 6, Price = 8.99m, Title = "The Cream Of Clapton" },
                        new { AlbumId = 70, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 50, GenreId = 6, Price = 8.99m, Title = "Unplugged" },
                        new { AlbumId = 71, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 51, GenreId = 10, Price = 8.99m, Title = "Respighi:Pines of Rome" },
                        new { AlbumId = 72, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 51, GenreId = 10, Price = 8.99m, Title = "Strauss: Waltzes" },
                        new { AlbumId = 73, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 52, GenreId = 1, Price = 8.99m, Title = "King For A Day Fool For A Lifetime" },
                        new { AlbumId = 74, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 53, GenreId = 7, Price = 8.99m, Title = "Deixa Entrar" },
                        new { AlbumId = 75, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 54, GenreId = 1, Price = 8.99m, Title = "In Your Honor [Disc 1]" },
                        new { AlbumId = 76, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 54, GenreId = 1, Price = 8.99m, Title = "In Your Honor [Disc 2]" },
                        new { AlbumId = 77, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 54, GenreId = 1, Price = 8.99m, Title = "The Colour And The Shape" },
                        new { AlbumId = 78, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 55, GenreId = 1, Price = 8.99m, Title = "Bongo Fury" },
                        new { AlbumId = 79, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 57, GenreId = 7, Price = 8.99m, Title = "Roda De Funk" },
                        new { AlbumId = 80, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 59, GenreId = 7, Price = 8.99m, Title = "Quanta Gente Veio Ver (Live)" },
                        new { AlbumId = 81, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 59, GenreId = 2, Price = 8.99m, Title = "Quanta Gente Veio ver--Bônus De Carnaval" },
                        new { AlbumId = 82, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 60, GenreId = 3, Price = 8.99m, Title = "Faceless" },
                        new { AlbumId = 83, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 61, GenreId = 7, Price = 8.99m, Title = "Meus Momentos" },
                        new { AlbumId = 84, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 62, GenreId = 10, Price = 8.99m, Title = "Nielsen: The Six Symphonies" },
                        new { AlbumId = 85, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 63, GenreId = 1, Price = 8.99m, Title = "Appetite for Destruction" },
                        new { AlbumId = 86, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 63, GenreId = 1, Price = 8.99m, Title = "Use Your Illusion I" },
                        new { AlbumId = 87, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 63, GenreId = 3, Price = 8.99m, Title = "Use Your Illusion II" },
                        new { AlbumId = 88, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 65, GenreId = 2, Price = 8.99m, Title = "Blue Moods" },
                        new { AlbumId = 89, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "A Matter of Life and Death" },
                        new { AlbumId = 90, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "Brave New World" },
                        new { AlbumId = 91, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "Fear Of The Dark" },
                        new { AlbumId = 92, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "Live At Donington 1992 (Disc 1)" },
                        new { AlbumId = 93, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "Live At Donington 1992 (Disc 2)" },
                        new { AlbumId = 94, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "Rock In Rio [CD2]" },
                        new { AlbumId = 95, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "The Number of The Beast" },
                        new { AlbumId = 96, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "The X Factor" },
                        new { AlbumId = 97, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 1, Price = 8.99m, Title = "Virtual XI" },
                        new { AlbumId = 98, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "A Real Dead One" },
                        new { AlbumId = 99, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "A Real Live One" },
                        new { AlbumId = 101, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "Live After Death" },
                        new { AlbumId = 102, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "No Prayer For The Dying" },
                        new { AlbumId = 103, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "Piece Of Mind" },
                        new { AlbumId = 104, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "Powerslave" },
                        new { AlbumId = 105, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "Rock In Rio [CD1]" },
                        new { AlbumId = 106, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "Rock In Rio [CD2]" },
                        new { AlbumId = 107, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "Seventh Son of a Seventh Son" },
                        new { AlbumId = 108, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "Somewhere in Time" },
                        new { AlbumId = 109, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 3, Price = 8.99m, Title = "The Number of The Beast" },
                        new { AlbumId = 110, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 66, GenreId = 6, Price = 8.99m, Title = "Iron Maiden" },
                        new { AlbumId = 111, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 67, GenreId = 10, Price = 8.99m, Title = "Mascagni: Cavalleria Rusticana" },
                        new { AlbumId = 112, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 68, GenreId = 1, Price = 8.99m, Title = "Emergency On Planet Earth" },
                        new { AlbumId = 113, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 69, GenreId = 1, Price = 8.99m, Title = "Are You Experienced?" },
                        new { AlbumId = 114, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 70, GenreId = 1, Price = 8.99m, Title = "Surfing with the Alien (Remastered)" },
                        new { AlbumId = 115, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 71, GenreId = 7, Price = 8.99m, Title = "Jorge Ben Jor 25 Anos" },
                        new { AlbumId = 116, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 72, GenreId = 7, Price = 8.99m, Title = "Jota Quest-1995" },
                        new { AlbumId = 117, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 73, GenreId = 3, Price = 8.99m, Title = "Living After Midnight" },
                        new { AlbumId = 118, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 75, GenreId = 10, Price = 8.99m, Title = "Weill: The Seven Deadly Sins" },
                        new { AlbumId = 119, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 76, GenreId = 1, Price = 8.99m, Title = "Greatest Kiss" },
                        new { AlbumId = 120, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 76, GenreId = 1, Price = 8.99m, Title = "Unplugged [Live]" },
                        new { AlbumId = 121, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "BBC Sessions [Disc 1] [Live]" },
                        new { AlbumId = 122, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "BBC Sessions [Disc 2] [Live]" },
                        new { AlbumId = 123, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Coda" },
                        new { AlbumId = 124, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Houses Of The Holy" },
                        new { AlbumId = 125, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "In Through The Out Door" },
                        new { AlbumId = 126, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "IV" },
                        new { AlbumId = 127, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Led Zeppelin I" },
                        new { AlbumId = 128, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Led Zeppelin II" },
                        new { AlbumId = 129, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Led Zeppelin III" },
                        new { AlbumId = 130, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Physical Graffiti [Disc 1]" },
                        new { AlbumId = 131, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Physical Graffiti [Disc 2]" },
                        new { AlbumId = 132, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "Presence" },
                        new { AlbumId = 133, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "The Song Remains The Same (Disc 1)" },
                        new { AlbumId = 134, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 77, GenreId = 1, Price = 8.99m, Title = "The Song Remains The Same (Disc 2)" },
                        new { AlbumId = 135, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 78, GenreId = 7, Price = 8.99m, Title = "Mais Do Mesmo" },
                        new { AlbumId = 136, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 79, GenreId = 8, Price = 8.99m, Title = "Greatest Hits" },
                        new { AlbumId = 137, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 79, GenreId = 1, Price = 8.99m, Title = "Greatest Hits" },
                        new { AlbumId = 138, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 79, GenreId = 3, Price = 8.99m, Title = "Greatest Hits" },
                        new { AlbumId = 139, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 81, GenreId = 10, Price = 8.99m, Title = "Tchaikovsky: The Nutcracker" },
                        new { AlbumId = 140, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 82, GenreId = 7, Price = 8.99m, Title = "Duos II" },
                        new { AlbumId = 141, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 84, GenreId = 7, Price = 8.99m, Title = "Chill: Brazil (Disc 1)" },
                        new { AlbumId = 142, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 85, GenreId = 1, Price = 8.99m, Title = "Misplaced Childhood" },
                        new { AlbumId = 143, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 86, GenreId = 7, Price = 8.99m, Title = "Barulhinho Bom" },
                        new { AlbumId = 144, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 87, GenreId = 10, Price = 8.99m, Title = "Szymanowski: Piano Works, Vol. 1" },
                        new { AlbumId = 145, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "...And Justice For All" },
                        new { AlbumId = 146, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "Black Album" },
                        new { AlbumId = 147, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "Garage Inc. (Disc 1)" },
                        new { AlbumId = 148, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "Garage Inc. (Disc 2)" },
                        new { AlbumId = 149, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "Load" },
                        new { AlbumId = 150, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "Master Of Puppets" },
                        new { AlbumId = 151, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "ReLoad" },
                        new { AlbumId = 152, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "Ride The Lightning" },
                        new { AlbumId = 153, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 91, GenreId = 3, Price = 8.99m, Title = "St. Anger" },
                        new { AlbumId = 154, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 92, GenreId = 10, Price = 8.99m, Title = "Berlioz: Symphonie Fantastique" },
                        new { AlbumId = 155, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 92, GenreId = 10, Price = 8.99m, Title = "Prokofiev: Romeo & Juliet" },
                        new { AlbumId = 156, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 93, GenreId = 2, Price = 8.99m, Title = "Miles Ahead" },
                        new { AlbumId = 157, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 93, GenreId = 2, Price = 8.99m, Title = "The Essential Miles Davis [Disc 1]" },
                        new { AlbumId = 158, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 93, GenreId = 2, Price = 8.99m, Title = "The Essential Miles Davis [Disc 2]" },
                        new { AlbumId = 159, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 94, GenreId = 7, Price = 8.99m, Title = "Milton Nascimento Ao Vivo" },
                        new { AlbumId = 160, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 94, GenreId = 7, Price = 8.99m, Title = "Minas" },
                        new { AlbumId = 161, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 95, GenreId = 3, Price = 8.99m, Title = "Motley Crue Greatest Hits" },
                        new { AlbumId = 162, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 96, GenreId = 3, Price = 8.99m, Title = "Ace Of Spades" },
                        new { AlbumId = 163, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 97, GenreId = 10, Price = 8.99m, Title = "Mozart: Chamber Music" },
                        new { AlbumId = 164, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 98, GenreId = 10, Price = 8.99m, Title = "The Best of Beethoven" },
                        new { AlbumId = 165, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 99, GenreId = 1, Price = 8.99m, Title = "Nevermind" },
                        new { AlbumId = 166, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 100, GenreId = 1, Price = 8.99m, Title = "Compositores" },
                        new { AlbumId = 167, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 101, GenreId = 7, Price = 8.99m, Title = "Olodum" },
                        new { AlbumId = 168, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 102, GenreId = 10, Price = 8.99m, Title = "Bach: The Brandenburg Concertos" },
                        new { AlbumId = 169, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 103, GenreId = 7, Price = 8.99m, Title = "Acústico MTV" },
                        new { AlbumId = 170, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 103, GenreId = 7, Price = 8.99m, Title = "Arquivo II" },
                        new { AlbumId = 171, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 103, GenreId = 7, Price = 8.99m, Title = "Arquivo Os Paralamas Do Sucesso" },
                        new { AlbumId = 172, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 104, GenreId = 3, Price = 8.99m, Title = "Tribute" },
                        new { AlbumId = 173, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 104, GenreId = 1, Price = 8.99m, Title = "Bark at the Moon (Remastered)" },
                        new { AlbumId = 174, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 104, GenreId = 1, Price = 8.99m, Title = "Blizzard of Ozz" },
                        new { AlbumId = 175, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 104, GenreId = 1, Price = 8.99m, Title = "Diary of a Madman (Remastered)" },
                        new { AlbumId = 176, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 104, GenreId = 1, Price = 8.99m, Title = "No More Tears (Remastered)" },
                        new { AlbumId = 177, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 104, GenreId = 1, Price = 8.99m, Title = "Speak of the Devil" },
                        new { AlbumId = 178, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 105, GenreId = 1, Price = 8.99m, Title = "Walking Into Clarksdale" },
                        new { AlbumId = 179, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 106, GenreId = 1, Price = 8.99m, Title = "The Beast Live" },
                        new { AlbumId = 180, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 107, GenreId = 1, Price = 8.99m, Title = "Live On Two Legs [Live]" },
                        new { AlbumId = 181, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 107, GenreId = 1, Price = 8.99m, Title = "Riot Act" },
                        new { AlbumId = 182, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 107, GenreId = 1, Price = 8.99m, Title = "Ten" },
                        new { AlbumId = 183, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 107, GenreId = 1, Price = 8.99m, Title = "Vs." },
                        new { AlbumId = 184, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 108, GenreId = 1, Price = 8.99m, Title = "Dark Side Of The Moon" },
                        new { AlbumId = 185, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 109, GenreId = 1, Price = 8.99m, Title = "Greatest Hits I" },
                        new { AlbumId = 186, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 109, GenreId = 1, Price = 8.99m, Title = "Greatest Hits II" },
                        new { AlbumId = 187, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 109, GenreId = 1, Price = 8.99m, Title = "News Of The World" },
                        new { AlbumId = 188, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 110, GenreId = 1, Price = 8.99m, Title = "New Adventures In Hi-Fi" },
                        new { AlbumId = 189, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 111, GenreId = 1, Price = 8.99m, Title = "Raul Seixas" },
                        new { AlbumId = 190, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 112, GenreId = 1, Price = 8.99m, Title = "By The Way" },
                        new { AlbumId = 191, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 112, GenreId = 1, Price = 8.99m, Title = "Californication" },
                        new { AlbumId = 192, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 113, GenreId = 10, Price = 8.99m, Title = "Purcell: The Fairy Queen" },
                        new { AlbumId = 193, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 114, GenreId = 10, Price = 8.99m, Title = "Haydn: Symphonies 99 - 104" },
                        new { AlbumId = 194, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 115, GenreId = 1, Price = 8.99m, Title = "Retrospective I (1974-1980)" },
                        new { AlbumId = 195, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 116, GenreId = 1, Price = 8.99m, Title = "Santana - As Years Go By" },
                        new { AlbumId = 196, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 116, GenreId = 1, Price = 8.99m, Title = "Santana Live" },
                        new { AlbumId = 197, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 116, GenreId = 1, Price = 8.99m, Title = "Supernatural" },
                        new { AlbumId = 198, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 117, GenreId = 10, Price = 8.99m, Title = "Handel: The Messiah (Highlights)" },
                        new { AlbumId = 199, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 119, GenreId = 10, Price = 8.99m, Title = "Prokofiev: Symphony No.1" },
                        new { AlbumId = 201, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 120, GenreId = 10, Price = 8.99m, Title = "Wagner: Favourite Overtures" },
                        new { AlbumId = 202, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 121, GenreId = 1, Price = 8.99m, Title = "Maquinarama" },
                        new { AlbumId = 203, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 121, GenreId = 1, Price = 8.99m, Title = "O Samba Poconé" },
                        new { AlbumId = 204, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 122, GenreId = 1, Price = 8.99m, Title = "A-Sides" },
                        new { AlbumId = 205, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 123, GenreId = 2, Price = 8.99m, Title = "Heart of the Night" },
                        new { AlbumId = 206, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 123, GenreId = 2, Price = 8.99m, Title = "Morning Dance" },
                        new { AlbumId = 207, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 124, GenreId = 6, Price = 8.99m, Title = "In Step" },
                        new { AlbumId = 208, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 125, GenreId = 1, Price = 8.99m, Title = "Core" },
                        new { AlbumId = 209, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 126, GenreId = 3, Price = 8.99m, Title = "Mezmerize" },
                        new { AlbumId = 210, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 127, GenreId = 4, Price = 8.99m, Title = "Temple of the Dog" },
                        new { AlbumId = 211, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 128, GenreId = 1, Price = 8.99m, Title = "[1997] Black Light Syndrome" },
                        new { AlbumId = 212, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 129, GenreId = 10, Price = 8.99m, Title = "South American Getaway" },
                        new { AlbumId = 213, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 130, GenreId = 6, Price = 8.99m, Title = "Live [Disc 1]" },
                        new { AlbumId = 214, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 130, GenreId = 6, Price = 8.99m, Title = "Live [Disc 2]" },
                        new { AlbumId = 215, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 131, GenreId = 1, Price = 8.99m, Title = "Beyond Good And Evil" },
                        new { AlbumId = 216, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 132, GenreId = 1, Price = 8.99m, Title = "The Doors" },
                        new { AlbumId = 217, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 133, GenreId = 10, Price = 8.99m, Title = "English Renaissance" },
                        new { AlbumId = 218, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 134, GenreId = 1, Price = 8.99m, Title = "The Police Greatest Hits" },
                        new { AlbumId = 219, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 135, GenreId = 1, Price = 8.99m, Title = "Every Kind of Light" },
                        new { AlbumId = 220, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 136, GenreId = 1, Price = 8.99m, Title = "Hot Rocks, 1964-1971 (Disc 1)" },
                        new { AlbumId = 221, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 136, GenreId = 1, Price = 8.99m, Title = "No Security" },
                        new { AlbumId = 222, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 136, GenreId = 1, Price = 8.99m, Title = "Voodoo Lounge" },
                        new { AlbumId = 223, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 137, GenreId = 1, Price = 8.99m, Title = "My Generation - The Very Best Of The Who" },
                        new { AlbumId = 224, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 138, GenreId = 7, Price = 8.99m, Title = "Serie Sem Limite (Disc 1)" },
                        new { AlbumId = 225, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 138, GenreId = 7, Price = 8.99m, Title = "Serie Sem Limite (Disc 2)" },
                        new { AlbumId = 226, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 139, GenreId = 10, Price = 8.99m, Title = "Bach: Toccata & Fugue in D Minor" },
                        new { AlbumId = 227, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "Achtung Baby" },
                        new { AlbumId = 228, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "B-Sides 1980-1990" },
                        new { AlbumId = 229, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "How To Dismantle An Atomic Bomb" },
                        new { AlbumId = 230, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "Pop" },
                        new { AlbumId = 231, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "Rattle And Hum" },
                        new { AlbumId = 232, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "The Best Of 1980-1990" },
                        new { AlbumId = 233, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "War" },
                        new { AlbumId = 234, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 140, GenreId = 1, Price = 8.99m, Title = "Zooropa" },
                        new { AlbumId = 235, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 141, GenreId = 8, Price = 8.99m, Title = "UB40 The Best Of - Volume Two [UK]" },
                        new { AlbumId = 236, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 142, GenreId = 1, Price = 8.99m, Title = "Diver Down" },
                        new { AlbumId = 237, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 142, GenreId = 1, Price = 8.99m, Title = "The Best Of Van Halen, Vol. I" },
                        new { AlbumId = 238, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 142, GenreId = 1, Price = 8.99m, Title = "Van Halen III" },
                        new { AlbumId = 239, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 142, GenreId = 1, Price = 8.99m, Title = "Van Halen" },
                        new { AlbumId = 240, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 143, GenreId = 9, Price = 8.99m, Title = "Axé Bahia 2001" },
                        new { AlbumId = 241, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 143, GenreId = 7, Price = 8.99m, Title = "Sambas De Enredo 2001" },
                        new { AlbumId = 242, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 143, GenreId = 7, Price = 8.99m, Title = "Vozes do MPB" },
                        new { AlbumId = 243, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 144, GenreId = 1, Price = 8.99m, Title = "Contraband" },
                        new { AlbumId = 244, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 145, GenreId = 7, Price = 8.99m, Title = "Vinicius De Moraes" },
                        new { AlbumId = 245, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 146, GenreId = 10, Price = 8.99m, Title = "Bach: Goldberg Variations" },
                        new { AlbumId = 246, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 147, GenreId = 10, Price = 8.99m, Title = "Bartok: Violin & Viola Concertos" },
                        new { AlbumId = 247, AlbumArtUrl = "/Content/Images/placeholder.gif", ArtistId = 148, GenreId = 10, Price = 8.99m, Title = "Bach: The Cello Suites" }
                    );
                });

            modelBuilder.Entity("MvcMusicStore.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new { ArtistId = 1, Name = "Aaron Copland & London Symphony Orchestra" },
                        new { ArtistId = 2, Name = "Aaron Goldberg" },
                        new { ArtistId = 3, Name = "AC/DC" },
                        new { ArtistId = 4, Name = "Accept" },
                        new { ArtistId = 5, Name = "Adrian Leaper & Doreen de Feis" },
                        new { ArtistId = 6, Name = "Aerosmith" },
                        new { ArtistId = 7, Name = "Aisha Duo" },
                        new { ArtistId = 8, Name = "Alanis Morissette" },
                        new { ArtistId = 9, Name = "Alberto Turco & Nova Schola Gregoriana" },
                        new { ArtistId = 10, Name = "Alice In Chains" },
                        new { ArtistId = 11, Name = "Amy Winehouse" },
                        new { ArtistId = 12, Name = "Anita Ward" },
                        new { ArtistId = 13, Name = "Antônio Carlos Jobim" },
                        new { ArtistId = 14, Name = "Apocalyptica" },
                        new { ArtistId = 15, Name = "Audioslave" },
                        new { ArtistId = 16, Name = "Barry Wordsworth & BBC Concert Orchestra" },
                        new { ArtistId = 17, Name = "Berliner Philharmoniker & Hans Rosbaud" },
                        new { ArtistId = 18, Name = "Berliner Philharmoniker & Herbert Von Karajan" },
                        new { ArtistId = 19, Name = "Billy Cobham" },
                        new { ArtistId = 20, Name = "Black Label Society" },
                        new { ArtistId = 21, Name = "Black Sabbath" },
                        new { ArtistId = 22, Name = "Boston Symphony Orchestra & Seiji Ozawa" },
                        new { ArtistId = 23, Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                        new { ArtistId = 24, Name = "Bruce Dickinson" },
                        new { ArtistId = 25, Name = "Buddy Guy" },
                        new { ArtistId = 26, Name = "Caetano Veloso" },
                        new { ArtistId = 27, Name = "Cake" },
                        new { ArtistId = 28, Name = "Calexico" },
                        new { ArtistId = 29, Name = "Cássia Eller" },
                        new { ArtistId = 30, Name = "Chic" },
                        new { ArtistId = 31, Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                        new { ArtistId = 32, Name = "Chico Buarque" },
                        new { ArtistId = 33, Name = "Chico Science & Nação Zumbi" },
                        new { ArtistId = 34, Name = "Choir Of Westminster Abbey & Simon Preston" },
                        new { ArtistId = 35, Name = "Chris Cornell" },
                        new { ArtistId = 36, Name = "Christopher O'Riley" },
                        new { ArtistId = 37, Name = "Cidade Negra" },
                        new { ArtistId = 38, Name = "Cláudio Zoli" },
                        new { ArtistId = 39, Name = "Creedence Clearwater Revival" },
                        new { ArtistId = 40, Name = "David Coverdale" },
                        new { ArtistId = 41, Name = "Deep Purple" },
                        new { ArtistId = 42, Name = "Dennis Chambers" },
                        new { ArtistId = 43, Name = "Djavan" },
                        new { ArtistId = 44, Name = "Donna Summer" },
                        new { ArtistId = 45, Name = "Dread Zeppelin" },
                        new { ArtistId = 46, Name = "Ed Motta" },
                        new { ArtistId = 47, Name = "Edo de Waart & San Francisco Symphony" },
                        new { ArtistId = 48, Name = "Elis Regina" },
                        new { ArtistId = 49, Name = "English Concert & Trevor Pinnock" },
                        new { ArtistId = 50, Name = "Eric Clapton" },
                        new { ArtistId = 51, Name = "Eugene Ormandy" },
                        new { ArtistId = 52, Name = "Faith No More" },
                        new { ArtistId = 53, Name = "Falamansa" },
                        new { ArtistId = 54, Name = "Foo Fighters" },
                        new { ArtistId = 55, Name = "Frank Zappa & Captain Beefheart" },
                        new { ArtistId = 56, Name = "Fretwork" },
                        new { ArtistId = 57, Name = "Funk Como Le Gusta" },
                        new { ArtistId = 58, Name = "Gerald Moore" },
                        new { ArtistId = 59, Name = "Gilberto Gil" },
                        new { ArtistId = 60, Name = "Godsmack" },
                        new { ArtistId = 61, Name = "Gonzaguinha" },
                        new { ArtistId = 62, Name = "Göteborgs Symfoniker & Neeme Järvi" },
                        new { ArtistId = 63, Name = "Guns N' Roses" },
                        new { ArtistId = 64, Name = "Gustav Mahler" },
                        new { ArtistId = 65, Name = "Incognito" },
                        new { ArtistId = 66, Name = "Iron Maiden" },
                        new { ArtistId = 67, Name = "James Levine" },
                        new { ArtistId = 68, Name = "Jamiroquai" },
                        new { ArtistId = 69, Name = "Jimi Hendrix" },
                        new { ArtistId = 70, Name = "Joe Satriani" },
                        new { ArtistId = 71, Name = "Jorge Ben" },
                        new { ArtistId = 72, Name = "Jota Quest" },
                        new { ArtistId = 73, Name = "Judas Priest" },
                        new { ArtistId = 74, Name = "Julian Bream" },
                        new { ArtistId = 75, Name = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                        new { ArtistId = 76, Name = "Kiss" },
                        new { ArtistId = 77, Name = "Led Zeppelin" },
                        new { ArtistId = 78, Name = "Legião Urbana" },
                        new { ArtistId = 79, Name = "Lenny Kravitz" },
                        new { ArtistId = 80, Name = "Les Arts Florissants & William Christie" },
                        new { ArtistId = 81, Name = "London Symphony Orchestra & Sir Charles Mackerras" },
                        new { ArtistId = 82, Name = "Luciana Souza/Romero Lubambo" },
                        new { ArtistId = 83, Name = "Lulu Santos" },
                        new { ArtistId = 84, Name = "Marcos Valle" },
                        new { ArtistId = 85, Name = "Marillion" },
                        new { ArtistId = 86, Name = "Marisa Monte" },
                        new { ArtistId = 87, Name = "Martin Roscoe" },
                        new { ArtistId = 88, Name = "Maurizio Pollini" },
                        new { ArtistId = 89, Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                        new { ArtistId = 90, Name = "Men At Work" },
                        new { ArtistId = 91, Name = "Metallica" },
                        new { ArtistId = 92, Name = "Michael Tilson Thomas & San Francisco Symphony" },
                        new { ArtistId = 93, Name = "Miles Davis" },
                        new { ArtistId = 94, Name = "Milton Nascimento" },
                        new { ArtistId = 95, Name = "Mötley Crüe" },
                        new { ArtistId = 96, Name = "Motörhead" },
                        new { ArtistId = 97, Name = "Nash Ensemble" },
                        new { ArtistId = 98, Name = "Nicolaus Esterhazy Sinfonia" },
                        new { ArtistId = 99, Name = "Nirvana" },
                        new { ArtistId = 100, Name = "O Terço" },
                        new { ArtistId = 101, Name = "Olodum" },
                        new { ArtistId = 102, Name = "Orchestra of The Age of Enlightenment" },
                        new { ArtistId = 103, Name = "Os Paralamas Do Sucesso" },
                        new { ArtistId = 104, Name = "Ozzy Osbourne" },
                        new { ArtistId = 105, Name = "Page & Plant" },
                        new { ArtistId = 106, Name = "Paul D'Ianno" },
                        new { ArtistId = 107, Name = "Pearl Jam" },
                        new { ArtistId = 108, Name = "Pink Floyd" },
                        new { ArtistId = 109, Name = "Queen" },
                        new { ArtistId = 110, Name = "R.E.M." },
                        new { ArtistId = 111, Name = "Raul Seixas" },
                        new { ArtistId = 112, Name = "Red Hot Chili Peppers" },
                        new { ArtistId = 113, Name = "Roger Norrington, London Classical Players" },
                        new { ArtistId = 114, Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                        new { ArtistId = 115, Name = "Rush" },
                        new { ArtistId = 116, Name = "Santana" },
                        new { ArtistId = 117, Name = "Scholars Baroque Ensemble" },
                        new { ArtistId = 118, Name = "Scorpions" },
                        new { ArtistId = 119, Name = "Sergei Prokofiev & Yuri Temirkanov" },
                        new { ArtistId = 120, Name = "Sir Georg Solti & Wiener Philharmoniker" },
                        new { ArtistId = 121, Name = "Skank" },
                        new { ArtistId = 122, Name = "Soundgarden" },
                        new { ArtistId = 123, Name = "Spyro Gyra" },
                        new { ArtistId = 124, Name = "Stevie Ray Vaughan & Double Trouble" },
                        new { ArtistId = 125, Name = "Stone Temple Pilots" },
                        new { ArtistId = 126, Name = "System Of A Down" },
                        new { ArtistId = 127, Name = "Temple of the Dog" },
                        new { ArtistId = 128, Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
                        new { ArtistId = 129, Name = "The 12 Cellists of The Berlin Philharmonic" },
                        new { ArtistId = 130, Name = "The Black Crowes" },
                        new { ArtistId = 131, Name = "The Cult" },
                        new { ArtistId = 132, Name = "The Doors" },
                        new { ArtistId = 133, Name = "The King's Singers" },
                        new { ArtistId = 134, Name = "The Police" },
                        new { ArtistId = 135, Name = "The Posies" },
                        new { ArtistId = 136, Name = "The Rolling Stones" },
                        new { ArtistId = 137, Name = "The Who" },
                        new { ArtistId = 138, Name = "Tim Maia" },
                        new { ArtistId = 139, Name = "Ton Koopman" },
                        new { ArtistId = 140, Name = "U2" },
                        new { ArtistId = 141, Name = "UB40" },
                        new { ArtistId = 142, Name = "Van Halen" },
                        new { ArtistId = 143, Name = "Various Artists" },
                        new { ArtistId = 144, Name = "Velvet Revolver" },
                        new { ArtistId = 145, Name = "Vinícius De Moraes" },
                        new { ArtistId = 146, Name = "Wilhelm Kempff" },
                        new { ArtistId = 147, Name = "Yehudi Menuhin" },
                        new { ArtistId = 148, Name = "Yo-Yo Ma" }
                    );
                });

            modelBuilder.Entity("MvcMusicStore.Models.Cart", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlbumId");

                    b.Property<string>("CartId");

                    b.Property<int>("Count");

                    b.Property<DateTime>("DateCreated");

                    b.HasKey("RecordId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MvcMusicStore.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new { GenreId = 1, Name = "Rock" },
                        new { GenreId = 2, Name = "Jazz" },
                        new { GenreId = 3, Name = "Metal" },
                        new { GenreId = 4, Name = "Alternative" },
                        new { GenreId = 5, Name = "Disco" },
                        new { GenreId = 6, Name = "Blues" },
                        new { GenreId = 7, Name = "Latin" },
                        new { GenreId = 8, Name = "Reggae" },
                        new { GenreId = 9, Name = "Pop" },
                        new { GenreId = 10, Name = "Classical" }
                    );
                });

            modelBuilder.Entity("MvcMusicStore.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(24);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<decimal>("Total");

                    b.Property<string>("Username");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MvcMusicStore.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlbumId");

                    b.Property<int>("OrderId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("MvcMusicStore.Models.Album", b =>
                {
                    b.HasOne("MvcMusicStore.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MvcMusicStore.Models.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MvcMusicStore.Models.Cart", b =>
                {
                    b.HasOne("MvcMusicStore.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MvcMusicStore.Models.OrderDetail", b =>
                {
                    b.HasOne("MvcMusicStore.Models.Album", "Album")
                        .WithMany("OrderDetails")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MvcMusicStore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
